### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Wyam.Recipe#12]
https://github.com/cake-contrib/Cake.Wyam.Recipe/commit/3ae98f85ef0fd1e6ba269d78bc9995894da76b93 has broken the build of Cake.Prca.Website:

```
Cake.exe : Error: C:/projects/cake-prca-website/tools/Cake.Wyam.Recipe/Content/asynchelper.cake(17,26): error CS1003: Syntax error, ',' expected
```

See https://ci.appveyor.com/project/cakecontrib/cake-prca-website/build/1.0.276

**Comment by devlead** [comment]
Yes until next release,  it will  requirs cake to be launched with the experimental flag.

**Comment by gep13** [comment]
Apologies about the @pascalberger I forgot to mention this to you.

I will be correcting this tonight if I have some time.  The Cake.Http addin has just been updated to allow a generic call to SendAsync, so the method that I have used in this recipe (which is to use @devlead's asynhelper.cake file) will no longer be required.

**Comment by devlead** [comment]
Pin your versions 😎

**Comment by gep13** [comment]
>@devlead said...
Pin your versions 😎

Yes, I was going to mention that as well 👍

**Comment by pascalberger** [comment]
Sure, I pinned it now. But I'm OK to have it use latest version in this case to find out issues in Wyam.Recipe when they are introduced, since this particular build is not critical :)

**Comment by gep13** [comment]
@pascalberger I have just pushed a commit into the Cake.Wyam.Recipe repo which switches to using Cake.Http, rather than the async helper.

Could you please take it for a spin and let me know how you get on with it?

**Comment by pascalberger** [comment]
@gep13 Works like a charm again

**Comment by gep13** [comment]
:+1:
