### ISSUE TITLE
Cake task builder is no longer generic

### ISSUE THREAD

**Issue by M-Zuber** [cake-contrib/Cake.Wyam.Recipe#20]
[The code in `tasks.cake`](https://github.com/cake-contrib/Cake.Wyam.Recipe/blob/ceae594d1d927983bc5497ee7b9c65b8d180f056/Cake.Wyam.Recipe/Content/tasks.cake#L3-L14) uses a generic version of `CakeTaskBuilder`, but it seems that it is no longer available.

**Comment by M-Zuber** [comment]
I did some more digging, and since `Cake` is pinned to `0.25.0` it should be working, but I am still getting errors in AppVeyor.
![image](https://user-images.githubusercontent.com/4746537/42549983-ab46dcfe-84d7-11e8-8d67-5b9b26ecae22.png)

**Comment by M-Zuber** [comment]
Addendum: My issue was that I did not pin the version of `Cake.Wyam.Recipe` that was being used in blog configuration.<br>
So MyGet was pulling down C.W.R 0.6.0 which for some reason is not respecting the pinned Cake version<br>
Once I pinned to 0.5.0 it works great

Quite confused as to what is going on as even the latest version on MyGet should _yes_ be using a pinned Cake version of `0.25.0`

**Comment by M-Zuber** [comment]
Then I am at a loss as to what caused the issue, because I _did_ pin Cake inside my blog config, and it would not build until I pinned C.W.R

Either way, how can I test changes I make if I want to get C.W.R to yes be working with the newest Cake?

**Comment by gep13** [comment]
@M-Zuber I have just made a quick change to Cake.Wyam.Recipe to include information about what version is being used.

You can see this being output here:

https://ci.appveyor.com/project/GaryEwanPark/gep13/build/0.1.0+276.build.132#L137

That is a brand new build of my blog, and it has succeeded successfully with that combination of tools.  Can you check to see if you are also using all the same versions?

**Comment by gep13** [comment]
@M-Zuber hmm, this is turning into a bigger job than I have time for at the minute...

I need to get Cake.Recipe updated to use 0.28.1 of Cake, before I can complete the work to update Cake.Wyam.Recipe.

You have to love dependency chaining...

**Comment by M-Zuber** [comment]
Thank you very much for looking into this!
https://ci.appveyor.com/project/M-Zuber/m-zuber-github-io#L108

seems to be working now, even with the latest version of CWR 😕 

I'll try my hand at getting Cake.Recipe updated, and then come back here

**Comment by gep13** [comment]
There is actually already an open PR to fix everything. I just need to sit down and test it out before pulling it all in.

**Comment by M-Zuber** [comment]
👍 
So then I'll close this out,

thanks again for having a look!
