### ISSUE TITLE
Remove GitVersion

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Wyam.Recipe#3]
The version calculated by GitVersion doesn't seem to be used except for debug output.

**Comment by gep13** [comment]
Actually, I have a plan for this...

If you look at a site like [chocolatey.org](https://chocolatey.org/) it includes information in the footer about what commit is actually running on the site.  I am planning on doing something similar.  I am going to take the asserted version number from GitVersion and pass this in as a Setting to the Wyam build, and then in the footer of the site, use this setting to write out the current version number.

**Comment by pascalberger** [comment]
Adding SHA to the footer makes sense, but are there really a lot of cases where documentation / website is versioned? 

Adding SHA can be done by using Cake.Git. Using versioning IMHO is an edge case and can be implemented using extension points if required.

**Comment by gep13** [comment]
@pascalberger you might be right. I will think this one over....
